stages:
  - build
  - test
  - deploy

job install:
  before_script:
    - which python3
    - which pip3
  stage: build
  script: pip3 install -r requirements.txt

job migrate:
  before_script:
    - python3 manage.py makemigrations rest
  stage: build
  script: python3 manage.py migrate rest

job run:
  before_script:
    - sh stop_cmdb.sh
  stage: build
  script: sh start_cmdb.sh

