stages:
  - build
  - test
  - deploy

job install:
  before_script:
    - which python3
    - which pip3
  stage: build
  script: pip3 install -r requirements.txt
  only:
    - master

job migrate:
  before_script:
    - python3 manage.py makemigrations rest
  stage: test
  script: python3 manage.py migrate rest
  only:
    - master

job run:
   before_script:
     - sh stop_cmdb.sh
   stage: deploy
   script: sh start_cmdb.sh
   only:
     - master

