stages:
  - build
  - test
  - deploy

job install:
  before_script:
    - which python3
    - which pip3
  stage: build
  script: pip3 install -r requirements.txt

job migrate:
  before_script:
    - python3 manage.py makemigrations rest
  stage: build
  script: python3 manage.py migrate rest

job run:
  before_script:
    - netstat -ntpl|grep 8000 |awk '{print $NF}'|awk -F/ '{cmd="kill -9" $1;system(cmd);}'
  stage:
  script: nohup python3 manage.py runserver 0.0.0.0:8000 &

