# Generated by Django 2.1.7 on 2019-04-28 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresource',
            name='departments',
            field=models.ManyToManyField(default=[], to='rest.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='leaders',
            field=models.ManyToManyField(default=[], related_name='leader_ships', to=settings.AUTH_USER_MODEL),
        ),
    ]
