# Generated by Django 2.1.7 on 2019-04-28 07:38

from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rest', '0002_auto_20190428_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseservice',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Tree node', 'verbose_name_plural': 'Tree nodes'},
        ),
        migrations.AlterModelOptions(
            name='mysqlservice',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Mysql Service', 'verbose_name_plural': 'Mysql Service'},
        ),
        migrations.AlterModelOptions(
            name='normalservice',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Normal Service', 'verbose_name_plural': 'Normal Service'},
        ),
        migrations.AddField(
            model_name='baseservice',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_rest.baseservice_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rest.BaseService'),
        ),
    ]
