# Generated by Django 2.1.7 on 2019-04-29 06:28

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_historicalbaseservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServerType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('_ctime', models.DateTimeField(blank=True, editable=False)),
                ('_mtime', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=64, verbose_name='机器类型')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical server type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
