# Generated by Django 2.1.7 on 2019-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20190505_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterface',
            name='type',
            field=models.CharField(choices=[('ipv4', 'ipv4'), ('ipv6', 'ipv6')], max_length=64),
        ),
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.CharField(choices=[('ipv4', 'ipv4'), ('ipv6', 'ipv6')], max_length=64),
        ),
    ]
