# Generated by Django 2.1.7 on 2019-05-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20190505_1952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('resource', 'type', 'address')},
        ),
        migrations.AlterIndexTogether(
            name='interface',
            index_together={('resource', 'type', 'address')},
        ),
    ]
