# Generated by Django 2.1.7 on 2019-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20190505_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnormalservice',
            name='git',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='normalservice',
            name='git',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
