# Generated by Django 2.1.7 on 2019-05-10 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20190509_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServiceLabel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('k', models.CharField(max_length=64, verbose_name='k')),
                ('v', models.CharField(max_length=64, verbose_name='v')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rest.BaseService')),
            ],
            options={
                'verbose_name': 'historical service label',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=64, verbose_name='k')),
                ('v', models.CharField(max_length=64, verbose_name='v')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='rest.BaseService')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servicelabel',
            unique_together={('service', 'k', 'v')},
        ),
        migrations.AlterIndexTogether(
            name='servicelabel',
            index_together={('service', 'k', 'v')},
        ),
    ]
