# Generated by Django 2.1.7 on 2019-05-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20190510_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='departments',
            field=models.ManyToManyField(default=[], to='rest.Department'),
        ),
    ]
