# Generated by Django 2.1.7 on 2019-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_baseservice_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db',
            name='extra_args',
        ),
        migrations.RemoveField(
            model_name='db',
            name='password',
        ),
        migrations.RemoveField(
            model_name='db',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dbinstance',
            name='manage_password',
        ),
        migrations.RemoveField(
            model_name='dbinstance',
            name='manage_user',
        ),
        migrations.RemoveField(
            model_name='dbservice',
            name='use_type',
        ),
        migrations.RemoveField(
            model_name='historicaldb',
            name='extra_args',
        ),
        migrations.RemoveField(
            model_name='historicaldb',
            name='password',
        ),
        migrations.RemoveField(
            model_name='historicaldb',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaldbinstance',
            name='manage_password',
        ),
        migrations.RemoveField(
            model_name='historicaldbinstance',
            name='manage_user',
        ),
        migrations.RemoveField(
            model_name='historicaldbservice',
            name='use_type',
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='info',
            field=models.CharField(help_text='详情描述字段', max_length=255),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='tree_path_cache',
            field=models.CharField(blank=True, help_text='不可编辑字段,描述路径缓存', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldbservice',
            name='info',
            field=models.CharField(help_text='详情描述字段', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldbservice',
            name='tree_path_cache',
            field=models.CharField(blank=True, help_text='不可编辑字段,描述路径缓存', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnormalservice',
            name='info',
            field=models.CharField(help_text='详情描述字段', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalnormalservice',
            name='tree_path_cache',
            field=models.CharField(blank=True, help_text='不可编辑字段,描述路径缓存', max_length=255, null=True),
        ),
    ]
