# Generated by Django 2.1.7 on 2019-05-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20190511_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinstance',
            name='base_resource',
        ),
        migrations.RemoveField(
            model_name='historicaldbinstance',
            name='base_resource',
        ),
        migrations.AddField(
            model_name='dbinstance',
            name='belong_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong_server', to='rest.Server'),
        ),
        migrations.AddField(
            model_name='historicaldbinstance',
            name='belong_server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rest.Server'),
        ),
    ]
