# Generated by Django 2.1.7 on 2019-05-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20190511_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresource',
            name='departments',
            field=models.ManyToManyField(blank=True, to='rest.Department'),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='departments',
            field=models.ManyToManyField(blank=True, to='rest.Department'),
        ),
        migrations.AlterField(
            model_name='historicalserviceresourcesrelation',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceresourcesrelation',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
