# Generated by Django 2.1.7 on 2019-04-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hook',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='httphook',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='hook',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_wfapp.hook_set+', to='contenttypes.ContentType'),
        ),
    ]
