# Generated by Django 2.1.7 on 2019-04-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfapp', '0002_auto_20190403_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='start_step_define',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wfapp.StepDefine'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='after_commit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_commit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='after_fail_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_fail_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='after_reject',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_reject_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='after_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='after_success_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_success_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='before_commit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_commit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='before_fail_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_fail_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='before_reject',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_reject_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='before_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='before_success_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_success_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='commit_steps',
            field=models.ManyToManyField(blank=True, default=[], related_name='commit_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='fail_steps',
            field=models.ManyToManyField(blank=True, default=[], related_name='fail_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='reject_steps',
            field=models.ManyToManyField(blank=True, default=[], related_name='reject_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='require_steps',
            field=models.ManyToManyField(blank=True, default=[], related_name='require_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='success_steps',
            field=models.ManyToManyField(blank=True, default=[], related_name='success_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AlterField(
            model_name='stepdefine',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_defines', to='wfapp.WorkflowTemplate'),
        ),
    ]
