# Generated by Django 2.1.7 on 2019-04-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfapp', '0003_auto_20190403_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepdefine',
            old_name='commit_steps',
            new_name='commit_stepdefines',
        ),
        migrations.RenameField(
            model_name='stepdefine',
            old_name='fail_steps',
            new_name='fail_stepdefines',
        ),
        migrations.RenameField(
            model_name='stepdefine',
            old_name='reject_steps',
            new_name='reject_stepdefines',
        ),
        migrations.RenameField(
            model_name='stepdefine',
            old_name='success_steps',
            new_name='success_stepdefines',
        ),
        migrations.RemoveField(
            model_name='stepdefine',
            name='require_steps',
        ),
    ]
